--------------------------------------------------------
--  Fichier créé - lundi-octobre-15-2012   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table EAE
--------------------------------------------------------

  CREATE TABLE "EAE"."EAE" 
   (	"ID_EAE" NUMBER(*,0), 
	"ID_CAMPAGNE_EAE" NUMBER(*,0), 
	"ID_AGENT" NUMBER(*,0), 
	"STATUT" VARCHAR2(10 BYTE), 
	"ETAT" VARCHAR2(2 BYTE), 
	"CAP" NUMBER(*,0), 
	"DOC_ATTACHE" NUMBER(*,0), 
	"DATE_CREATION" DATE, 
	"DATE_FIN" DATE, 
	"DATE_ENTRETIEN" DATE, 
	"DUREE_ENTRETIEN" NUMBER(*,0), 
	"DATE_FINALISE" DATE, 
	"DATE_CONTROLE" DATE, 
	"HEURE_CONTROLE" VARCHAR2(5 BYTE), 
	"USER_CONTROLE" VARCHAR2(7 BYTE), 
	"ID_DELEGATAIRE" NUMBER(*,0), 
	"VERSION" NUMBER DEFAULT 0
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table EAE_APPRECIATION
--------------------------------------------------------

  CREATE TABLE "EAE"."EAE_APPRECIATION" 
   (	"ID_EAE_APPRECIATION" NUMBER(*,0), 
	"ID_EAE" NUMBER(*,0), 
	"NUMERO" VARCHAR2(50 BYTE), 
	"NOTE_EVALUE" VARCHAR2(1 BYTE), 
	"NOTE_EVALUATEUR" VARCHAR2(1 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table EAE_AUTO_EVALUATION
--------------------------------------------------------

  CREATE TABLE "EAE"."EAE_AUTO_EVALUATION" 
   (	"ID_EAE_AUTO_EVALUATION" NUMBER(*,0), 
	"ID_EAE" NUMBER(*,0), 
	"ELEMENT" VARCHAR2(255 BYTE), 
	"OBJECTIF_ATTEINT" VARCHAR2(255 BYTE), 
	"COMPETENCES_ACQUISES" VARCHAR2(255 BYTE), 
	"SUCCES" VARCHAR2(255 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table EAE_CAMPAGNE_ACTEURS
--------------------------------------------------------

  CREATE TABLE "EAE"."EAE_CAMPAGNE_ACTEURS" 
   (	"ID_CAMPAGNE_ACTEURS" NUMBER(*,0), 
	"ID_CAMPAGNE_ACTION" NUMBER(*,0), 
	"ID_AGENT" NUMBER(*,0)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table EAE_CAMPAGNE_ACTION
--------------------------------------------------------

  CREATE TABLE "EAE"."EAE_CAMPAGNE_ACTION" 
   (	"ID_CAMPAGNE_ACTION" NUMBER(*,0), 
	"ID_CAMPAGNE_EAE" NUMBER(*,0), 
	"NOM_ACTION" VARCHAR2(50 BYTE), 
	"MESSAGE" VARCHAR2(100 BYTE), 
	"DATE_TRANSMISSION" DATE, 
	"DIFFUSE" NUMBER(*,0), 
	"DATE_A_FAIRE_LE" DATE, 
	"DATE_FAIT_LE" DATE, 
	"COMMENTAIRE" VARCHAR2(255 BYTE), 
	"ID_AGENT_REALISATION" NUMBER(*,0)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table EAE_CAMPAGNE_EAE
--------------------------------------------------------

  CREATE TABLE "EAE"."EAE_CAMPAGNE_EAE" 
   (	"ID_CAMPAGNE_EAE" NUMBER(*,0), 
	"ANNEE" NUMBER(*,0), 
	"DATE_DEBUT" DATE, 
	"DATE_FIN" DATE, 
	"DATE_OUVERTURE_KIOSQUE" DATE, 
	"DATE_FERMETURE_KIOSQUE" DATE, 
	"COMMENTAIRE" VARCHAR2(255 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table EAE_DEVELOPPEMENT
--------------------------------------------------------

  CREATE TABLE "EAE"."EAE_DEVELOPPEMENT" 
   (	"ID_EAE_DEVELOPPEMENT" NUMBER(*,0), 
	"ID_EAE" NUMBER(*,0), 
	"ID_TYPE_DEVELOPPEMENT" NUMBER(*,0), 
	"LIBELLE_DEVELOPPEMENT" VARCHAR2(255 BYTE), 
	"ECHEANCE_DEVELOPPEMENT" VARCHAR2(50 BYTE), 
	"PRIORISATION_DEVELOPPEMENT" NUMBER(*,0)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table EAE_DIPLOME
--------------------------------------------------------

  CREATE TABLE "EAE"."EAE_DIPLOME" 
   (	"ID_EAE_DIPLOME" NUMBER(*,0), 
	"ID_EAE" NUMBER(*,0), 
	"LIBELLE_DIPLOME" VARCHAR2(255 BYTE), 
	"VERSION" NUMBER
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table EAE_DOCUMENT
--------------------------------------------------------

  CREATE TABLE "EAE"."EAE_DOCUMENT" 
   (	"ID_EAE_DOCUMENT" NUMBER(*,0), 
	"ID_CAMPAGNE_EAE" NUMBER(*,0), 
	"ID_CAMPAGNE_ACTION" NUMBER(*,0), 
	"ID_DOCUMENT" NUMBER(*,0), 
	"TYPE_DOCUMENT" VARCHAR2(30 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table EAE_EVALUATEUR
--------------------------------------------------------

  CREATE TABLE "EAE"."EAE_EVALUATEUR" 
   (	"ID_EAE_EVALUATEUR" NUMBER(*,0), 
	"ID_EAE" NUMBER(*,0), 
	"ID_AGENT" NUMBER(*,0), 
	"FONCTION" VARCHAR2(100 BYTE), 
	"DATE_ENTREE_SERVICE" DATE, 
	"DATE_ENTREE_COLLECTIVITE" DATE, 
	"DATE_ENTREE_FONCTION" DATE, 
	"VERSION" NUMBER DEFAULT 0
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table EAE_EVALUATION
--------------------------------------------------------

  CREATE TABLE "EAE"."EAE_EVALUATION" 
   (	"ID_EAE_EVALUATION" NUMBER(*,0), 
	"ID_EAE" NUMBER(*,0), 
	"ID_EAE_NIVEAU" NUMBER(*,0), 
	"NOTE_ANNEE" NUMBER(4,2), 
	"NOTE_ANNEE_N1" NUMBER(4,2), 
	"NOTE_ANNEE_N2" NUMBER(4,2), 
	"NOTE_ANNEE_N3" NUMBER(4,2), 
	"AVIS" VARCHAR2(50 BYTE), 
	"AVANCEMENT_DIFF" VARCHAR2(50 BYTE), 
	"CHANGEMENT_CLASSE" VARCHAR2(50 BYTE), 
	"AVIS_SHD" VARCHAR2(50 BYTE), 
	"VERSION" NUMBER
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table EAE_EVALUE
--------------------------------------------------------

  CREATE TABLE "EAE"."EAE_EVALUE" 
   (	"ID_EAE_EVALUE" NUMBER(*,0), 
	"ID_EAE" NUMBER(*,0), 
	"ID_AGENT" NUMBER(*,0), 
	"DATE_ENTREE_SERVICE" DATE, 
	"DATE_ENTREE_COLLECTIVITE" DATE, 
	"DATE_ENTREE_FONCTIONNAIRE" DATE, 
	"DATE_ENTREE_ADMINISTRATION" DATE, 
	"STATUT" VARCHAR2(10 BYTE), 
	"ANCIENNETE_ECHELON" NUMBER(*,0), 
	"CADRE" VARCHAR2(30 BYTE), 
	"CATEGORIE" VARCHAR2(1 BYTE), 
	"CLASSIFICATION" VARCHAR2(50 BYTE), 
	"GRADE" VARCHAR2(50 BYTE), 
	"ECHELON" VARCHAR2(60 BYTE), 
	"DATE_EFFET_AVCT" DATE, 
	"NOUV_GRADE" VARCHAR2(50 BYTE), 
	"NOUV_ECHELON" VARCHAR2(60 BYTE), 
	"POSITION" VARCHAR2(50 BYTE), 
	"TYPE_AVCT" NUMBER(*,0), 
	"VERSION" NUMBER
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table EAE_EVOL_SOUHAIT
--------------------------------------------------------

  CREATE TABLE "EAE"."EAE_EVOL_SOUHAIT" 
   (	"ID_EAE_EVOL_SOUHAIT" NUMBER(*,0), 
	"ID_EAE" NUMBER(*,0), 
	"TYPE_SOUHAIT" VARCHAR2(50 BYTE), 
	"LIB_SOUHAIT" VARCHAR2(255 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table EAE_EVOLUTION
--------------------------------------------------------

  CREATE TABLE "EAE"."EAE_EVOLUTION" 
   (	"ID_EAE_EVOLUTION" NUMBER(*,0), 
	"ID_EAE" NUMBER(*,0), 
	"MOBILIE_GEO" NUMBER(*,0), 
	"MOBILIE_FONCT" NUMBER(*,0), 
	"CHANGEMENT_METIER" NUMBER(*,0), 
	"DELAI_ENVISAGE" VARCHAR2(50 BYTE), 
	"MOBILITE_SERVICE" NUMBER(*,0), 
	"MOBILITE_DIRECTION" NUMBER(*,0), 
	"MOBILITE_COLLECTIVITE" NUMBER(*,0), 
	"MOBILITE_AUTRE" NUMBER(*,0), 
	"NOM_ENTITE" VARCHAR2(100 BYTE), 
	"CONCOURS" NUMBER(*,0), 
	"NOM_CONCOURS" VARCHAR2(100 BYTE), 
	"DEMANDE_VAE" NUMBER(*,0), 
	"NOM_DIPLOME" VARCHAR2(100 BYTE), 
	"TEMPS_PARTIEL" NUMBER(*,0), 
	"POURC_TEMPS_PARTIEL" NUMBER(*,0), 
	"RETRAITE" NUMBER(*,0), 
	"DATE_RETRAITE" DATE, 
	"AUTRE_PERSPECTIVE" NUMBER(*,0), 
	"PERSPECTIVE" VARCHAR2(255 BYTE), 
	"COMMENTAIRE" VARCHAR2(255 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table EAE_FDP_ACTIVITE
--------------------------------------------------------

  CREATE TABLE "EAE"."EAE_FDP_ACTIVITE" 
   (	"ID_EAE_FDP_ACTIVITE" NUMBER(*,0), 
	"ID_EAE_FICHE_POSTE" NUMBER(*,0), 
	"TYPE_ACTIVITE" VARCHAR2(100 BYTE), 
	"LIBELLE_ACTIVITE" VARCHAR2(255 BYTE), 
	"VERSION" NUMBER
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table EAE_FICHE_POSTE
--------------------------------------------------------

  CREATE TABLE "EAE"."EAE_FICHE_POSTE" 
   (	"ID_EAE_FICHE_POSTE" NUMBER(*,0), 
	"ID_EAE" NUMBER(*,0), 
	"TYPE_FDP" VARCHAR2(60 BYTE), 
	"DIRECTION_SERVICE" VARCHAR2(60 BYTE), 
	"SERVICE" VARCHAR2(60 BYTE), 
	"SECTION_SERVICE" VARCHAR2(60 BYTE), 
	"EMPLOI" VARCHAR2(100 BYTE), 
	"FONCTION" VARCHAR2(100 BYTE), 
	"DATE_ENTREE_FONCTION" DATE, 
	"GRADE_POSTE" VARCHAR2(50 BYTE), 
	"LOCALISATION" VARCHAR2(60 BYTE), 
	"MISSIONS" CLOB, 
	"FONCTION_RESP" VARCHAR2(100 BYTE), 
	"ID_SHD" NUMBER, 
	"VERSION" NUMBER, 
	"DATE_ENTREE_SERVICE_RESP" DATE, 
	"DATE_ENTREE_COLLECT_RESP" DATE, 
	"DATE_ENTREE_FONCTION_RESP" DATE, 
	"CODE_SERVICE" VARCHAR2(4 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM" 
 LOB ("MISSIONS") STORE AS (
  TABLESPACE "SYSTEM" ENABLE STORAGE IN ROW CHUNK 8192 PCTVERSION 10
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)) ;
--------------------------------------------------------
--  DDL for Table EAE_FORMATION
--------------------------------------------------------

  CREATE TABLE "EAE"."EAE_FORMATION" 
   (	"ID_EAE_FORMATION" NUMBER(*,0), 
	"ID_EAE" NUMBER(*,0), 
	"ANNEE_FORMATION" NUMBER(*,0), 
	"DUREE_FORMATION" NUMBER(*,0), 
	"LIBELLE_FORMATION" VARCHAR2(255 BYTE), 
	"VERSION" NUMBER
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table EAE_NIVEAU
--------------------------------------------------------

  CREATE TABLE "EAE"."EAE_NIVEAU" 
   (	"ID_EAE_NIVEAU" NUMBER(*,0), 
	"LIBELLE_NIVEAU_EAE" VARCHAR2(50 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table EAE_PARCOURS_PRO
--------------------------------------------------------

  CREATE TABLE "EAE"."EAE_PARCOURS_PRO" 
   (	"ID_EAE_PARCOURS_PRO" NUMBER(*,0), 
	"ID_EAE" NUMBER(*,0), 
	"DATE_DEBUT" DATE, 
	"DATE_FIN" DATE, 
	"LIBELLE_PARCOURS_PRO" VARCHAR2(255 BYTE), 
	"VERSION" NUMBER
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table EAE_PLAN_ACTION
--------------------------------------------------------

  CREATE TABLE "EAE"."EAE_PLAN_ACTION" 
   (	"ID_EAE_PLAN_ACTION" NUMBER(*,0), 
	"ID_EAE" NUMBER(*,0), 
	"ID_EAE_TYPE_OBJECTIF" NUMBER(*,0), 
	"OBJECTIF" VARCHAR2(255 BYTE), 
	"MESURE" VARCHAR2(255 BYTE), 
	"VERSION" NUMBER DEFAULT 0
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table EAE_RESULTAT
--------------------------------------------------------

  CREATE TABLE "EAE"."EAE_RESULTAT" 
   (	"ID_EAE_RESULTAT" NUMBER(*,0), 
	"ID_EAE" NUMBER(*,0), 
	"ID_EAE_TYPE_OBJECTIF" NUMBER(*,0), 
	"OBJECTIF" VARCHAR2(255 BYTE), 
	"RESULTAT" VARCHAR2(255 BYTE), 
	"COMMENTAIRE" VARCHAR2(255 BYTE), 
	"VERSION" NUMBER
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table EAE_TYPE_DEVELOPPEMENT
--------------------------------------------------------

  CREATE TABLE "EAE"."EAE_TYPE_DEVELOPPEMENT" 
   (	"ID_EAE_TYPE_DEVELOPPEMENT" NUMBER(*,0), 
	"LIBELLE_TYPE_DEVELOPPEMENT" VARCHAR2(50 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table EAE_TYPE_OBJECTIF
--------------------------------------------------------

  CREATE TABLE "EAE"."EAE_TYPE_OBJECTIF" 
   (	"ID_EAE_TYPE_OBJECTIF" NUMBER(*,0), 
	"LIBELLE_TYPE_OBJECTIF" VARCHAR2(50 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM" ;

REM INSERTING into EAE.EAE_CAMPAGNE_ACTEURS
SET DEFINE OFF;
Insert into EAE.EAE_CAMPAGNE_ACTEURS (ID_CAMPAGNE_ACTEURS,ID_CAMPAGNE_ACTION,ID_AGENT) values ('27','64','9002962');
Insert into EAE.EAE_CAMPAGNE_ACTEURS (ID_CAMPAGNE_ACTEURS,ID_CAMPAGNE_ACTION,ID_AGENT) values ('28','64','9003052');
Insert into EAE.EAE_CAMPAGNE_ACTEURS (ID_CAMPAGNE_ACTEURS,ID_CAMPAGNE_ACTION,ID_AGENT) values ('29','65','9002962');
Insert into EAE.EAE_CAMPAGNE_ACTEURS (ID_CAMPAGNE_ACTEURS,ID_CAMPAGNE_ACTION,ID_AGENT) values ('30','65','9003052');
REM INSERTING into EAE.EAE_CAMPAGNE_ACTION
SET DEFINE OFF;
Insert into EAE.EAE_CAMPAGNE_ACTION (ID_CAMPAGNE_ACTION,ID_CAMPAGNE_EAE,NOM_ACTION,MESSAGE,DATE_TRANSMISSION,DIFFUSE,DATE_A_FAIRE_LE,DATE_FAIT_LE,COMMENTAIRE,ID_AGENT_REALISATION) values ('64','41','action 1.1','test',to_date('01/10/11','DD/MM/RR'),'0',to_date('29/10/11','DD/MM/RR'),null,'observation 1.1','9005237');
Insert into EAE.EAE_CAMPAGNE_ACTION (ID_CAMPAGNE_ACTION,ID_CAMPAGNE_EAE,NOM_ACTION,MESSAGE,DATE_TRANSMISSION,DIFFUSE,DATE_A_FAIRE_LE,DATE_FAIT_LE,COMMENTAIRE,ID_AGENT_REALISATION) values ('65','42','action 1.1','test',to_date('01/10/12','DD/MM/RR'),'0',to_date('29/10/12','DD/MM/RR'),null,null,'9005237');
REM INSERTING into EAE.EAE_CAMPAGNE_EAE
SET DEFINE OFF;
Insert into EAE.EAE_CAMPAGNE_EAE (ID_CAMPAGNE_EAE,ANNEE,DATE_DEBUT,DATE_FIN,DATE_OUVERTURE_KIOSQUE,DATE_FERMETURE_KIOSQUE,COMMENTAIRE) values ('41','2012',to_date('01/09/11','DD/MM/RR'),to_date('26/09/12','DD/MM/RR'),to_date('26/09/12','DD/MM/RR'),to_date('26/09/12','DD/MM/RR'),'premiere camp');
Insert into EAE.EAE_CAMPAGNE_EAE (ID_CAMPAGNE_EAE,ANNEE,DATE_DEBUT,DATE_FIN,DATE_OUVERTURE_KIOSQUE,DATE_FERMETURE_KIOSQUE,COMMENTAIRE) values ('42','2013',to_date('01/09/12','DD/MM/RR'),null,to_date('26/09/12','DD/MM/RR'),null,null);

REM INSERTING into EAE.EAE_NIVEAU
SET DEFINE OFF;
Insert into EAE.EAE_NIVEAU (ID_EAE_NIVEAU,LIBELLE_NIVEAU_EAE) values ('1','EXCELLENT');
Insert into EAE.EAE_NIVEAU (ID_EAE_NIVEAU,LIBELLE_NIVEAU_EAE) values ('2','SATISFAISANT');
Insert into EAE.EAE_NIVEAU (ID_EAE_NIVEAU,LIBELLE_NIVEAU_EAE) values ('3','NECESSITANT DES PROGRES');
Insert into EAE.EAE_NIVEAU (ID_EAE_NIVEAU,LIBELLE_NIVEAU_EAE) values ('4','INSUFFISANT');

REM INSERTING into EAE.EAE_TYPE_DEVELOPPEMENT
SET DEFINE OFF;
Insert into EAE.EAE_TYPE_DEVELOPPEMENT (ID_EAE_TYPE_DEVELOPPEMENT,LIBELLE_TYPE_DEVELOPPEMENT) values ('1','CONNAISSANCE');
Insert into EAE.EAE_TYPE_DEVELOPPEMENT (ID_EAE_TYPE_DEVELOPPEMENT,LIBELLE_TYPE_DEVELOPPEMENT) values ('2','COMPETENCE');
Insert into EAE.EAE_TYPE_DEVELOPPEMENT (ID_EAE_TYPE_DEVELOPPEMENT,LIBELLE_TYPE_DEVELOPPEMENT) values ('3','CONCOURS');
Insert into EAE.EAE_TYPE_DEVELOPPEMENT (ID_EAE_TYPE_DEVELOPPEMENT,LIBELLE_TYPE_DEVELOPPEMENT) values ('4','PERSONNEL');
Insert into EAE.EAE_TYPE_DEVELOPPEMENT (ID_EAE_TYPE_DEVELOPPEMENT,LIBELLE_TYPE_DEVELOPPEMENT) values ('5','COMPORTEMENT');
Insert into EAE.EAE_TYPE_DEVELOPPEMENT (ID_EAE_TYPE_DEVELOPPEMENT,LIBELLE_TYPE_DEVELOPPEMENT) values ('6','FORMATEUR');
REM INSERTING into EAE.EAE_TYPE_OBJECTIF
SET DEFINE OFF;
Insert into EAE.EAE_TYPE_OBJECTIF (ID_EAE_TYPE_OBJECTIF,LIBELLE_TYPE_OBJECTIF) values ('21','PROFESSIONNEL');
Insert into EAE.EAE_TYPE_OBJECTIF (ID_EAE_TYPE_OBJECTIF,LIBELLE_TYPE_OBJECTIF) values ('22','INDIVIDUEL');
Insert into EAE.EAE_TYPE_OBJECTIF (ID_EAE_TYPE_OBJECTIF,LIBELLE_TYPE_OBJECTIF) values ('23','MATERIELS');
Insert into EAE.EAE_TYPE_OBJECTIF (ID_EAE_TYPE_OBJECTIF,LIBELLE_TYPE_OBJECTIF) values ('24','FINANCIERS');
Insert into EAE.EAE_TYPE_OBJECTIF (ID_EAE_TYPE_OBJECTIF,LIBELLE_TYPE_OBJECTIF) values ('25','AUTRES');
--------------------------------------------------------
--  DDL for Index PK_EAE
--------------------------------------------------------

  CREATE UNIQUE INDEX "EAE"."PK_EAE" ON "EAE"."EAE" ("ID_EAE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index EAE_INDEX
--------------------------------------------------------

  CREATE UNIQUE INDEX "EAE"."EAE_INDEX" ON "EAE"."EAE" ("ID_CAMPAGNE_EAE", "ID_AGENT") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PK_EAE_APPRECIATION
--------------------------------------------------------

  CREATE UNIQUE INDEX "EAE"."PK_EAE_APPRECIATION" ON "EAE"."EAE_APPRECIATION" ("ID_EAE_APPRECIATION") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index EAE_APPRECIATION_INDEX
--------------------------------------------------------

  CREATE UNIQUE INDEX "EAE"."EAE_APPRECIATION_INDEX" ON "EAE"."EAE_APPRECIATION" ("ID_EAE", "NUMERO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PK_EAE_AUTO_EVALUATION
--------------------------------------------------------

  CREATE UNIQUE INDEX "EAE"."PK_EAE_AUTO_EVALUATION" ON "EAE"."EAE_AUTO_EVALUATION" ("ID_EAE_AUTO_EVALUATION") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PK_CAMPAGNE_ACTEURS
--------------------------------------------------------

  CREATE UNIQUE INDEX "EAE"."PK_CAMPAGNE_ACTEURS" ON "EAE"."EAE_CAMPAGNE_ACTEURS" ("ID_CAMPAGNE_ACTEURS") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PK_CAMPAGNE_ACTION
--------------------------------------------------------

  CREATE UNIQUE INDEX "EAE"."PK_CAMPAGNE_ACTION" ON "EAE"."EAE_CAMPAGNE_ACTION" ("ID_CAMPAGNE_ACTION") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PK_CAMPAGNE_EAE
--------------------------------------------------------

  CREATE UNIQUE INDEX "EAE"."PK_CAMPAGNE_EAE" ON "EAE"."EAE_CAMPAGNE_EAE" ("ID_CAMPAGNE_EAE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PK_EAE_DEVELOPPEMENT
--------------------------------------------------------

  CREATE UNIQUE INDEX "EAE"."PK_EAE_DEVELOPPEMENT" ON "EAE"."EAE_DEVELOPPEMENT" ("ID_EAE_DEVELOPPEMENT") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PK_EAE_DIPLOME
--------------------------------------------------------

  CREATE UNIQUE INDEX "EAE"."PK_EAE_DIPLOME" ON "EAE"."EAE_DIPLOME" ("ID_EAE_DIPLOME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index EAE_DIPLOME_INDEX
--------------------------------------------------------

  CREATE UNIQUE INDEX "EAE"."EAE_DIPLOME_INDEX" ON "EAE"."EAE_DIPLOME" ("ID_EAE", "LIBELLE_DIPLOME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PK_EAE_DOCUMENT
--------------------------------------------------------

  CREATE UNIQUE INDEX "EAE"."PK_EAE_DOCUMENT" ON "EAE"."EAE_DOCUMENT" ("ID_EAE_DOCUMENT") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PK_EAE_EVALUATEUR
--------------------------------------------------------

  CREATE UNIQUE INDEX "EAE"."PK_EAE_EVALUATEUR" ON "EAE"."EAE_EVALUATEUR" ("ID_EAE_EVALUATEUR") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index EAE_EVALUATEUR_INDEX
--------------------------------------------------------

  CREATE UNIQUE INDEX "EAE"."EAE_EVALUATEUR_INDEX" ON "EAE"."EAE_EVALUATEUR" ("ID_EAE", "ID_AGENT") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PK_EAE_EVALUATION
--------------------------------------------------------

  CREATE UNIQUE INDEX "EAE"."PK_EAE_EVALUATION" ON "EAE"."EAE_EVALUATION" ("ID_EAE_EVALUATION") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PK_EAE_EVALUE
--------------------------------------------------------

  CREATE UNIQUE INDEX "EAE"."PK_EAE_EVALUE" ON "EAE"."EAE_EVALUE" ("ID_EAE_EVALUE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index EAE_EVALUE_INDEX
--------------------------------------------------------

  CREATE UNIQUE INDEX "EAE"."EAE_EVALUE_INDEX" ON "EAE"."EAE_EVALUE" ("ID_EAE", "ID_AGENT") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PK_EAE_EVOL_SOUHAIT
--------------------------------------------------------

  CREATE UNIQUE INDEX "EAE"."PK_EAE_EVOL_SOUHAIT" ON "EAE"."EAE_EVOL_SOUHAIT" ("ID_EAE_EVOL_SOUHAIT") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PK_EAE_EVOLUTION
--------------------------------------------------------

  CREATE UNIQUE INDEX "EAE"."PK_EAE_EVOLUTION" ON "EAE"."EAE_EVOLUTION" ("ID_EAE_EVOLUTION") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PK_EAE_FDP_ACTIVITES
--------------------------------------------------------

  CREATE UNIQUE INDEX "EAE"."PK_EAE_FDP_ACTIVITES" ON "EAE"."EAE_FDP_ACTIVITE" ("ID_EAE_FDP_ACTIVITE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index EAE_FDP_ACTIVITES_INDEX
--------------------------------------------------------

  CREATE UNIQUE INDEX "EAE"."EAE_FDP_ACTIVITES_INDEX" ON "EAE"."EAE_FDP_ACTIVITE" ("ID_EAE_FICHE_POSTE", "TYPE_ACTIVITE", "LIBELLE_ACTIVITE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PK_EAE_FICHE_POSTE
--------------------------------------------------------

  CREATE UNIQUE INDEX "EAE"."PK_EAE_FICHE_POSTE" ON "EAE"."EAE_FICHE_POSTE" ("ID_EAE_FICHE_POSTE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PK_EAE_FORMATION
--------------------------------------------------------

  CREATE UNIQUE INDEX "EAE"."PK_EAE_FORMATION" ON "EAE"."EAE_FORMATION" ("ID_EAE_FORMATION") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index EAE_FORMATION_INDEX
--------------------------------------------------------

  CREATE UNIQUE INDEX "EAE"."EAE_FORMATION_INDEX" ON "EAE"."EAE_FORMATION" ("ID_EAE", "LIBELLE_FORMATION") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PK_EAE_NIVEAU_EAE
--------------------------------------------------------

  CREATE UNIQUE INDEX "EAE"."PK_EAE_NIVEAU_EAE" ON "EAE"."EAE_NIVEAU" ("ID_EAE_NIVEAU") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PK_EAE_PARCOURS_PRO
--------------------------------------------------------

  CREATE UNIQUE INDEX "EAE"."PK_EAE_PARCOURS_PRO" ON "EAE"."EAE_PARCOURS_PRO" ("ID_EAE_PARCOURS_PRO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index EAE_PARCOURS_PRO_INDEX
--------------------------------------------------------

  CREATE UNIQUE INDEX "EAE"."EAE_PARCOURS_PRO_INDEX" ON "EAE"."EAE_PARCOURS_PRO" ("ID_EAE", "DATE_DEBUT") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PK_EAE_PLAN_ACTION
--------------------------------------------------------

  CREATE UNIQUE INDEX "EAE"."PK_EAE_PLAN_ACTION" ON "EAE"."EAE_PLAN_ACTION" ("ID_EAE_PLAN_ACTION") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index EAE_PLAN_ACTION_INDEX
--------------------------------------------------------

  CREATE UNIQUE INDEX "EAE"."EAE_PLAN_ACTION_INDEX" ON "EAE"."EAE_PLAN_ACTION" ("ID_EAE", "ID_EAE_TYPE_OBJECTIF", "OBJECTIF") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index EAE_RESULTAT_INDEX
--------------------------------------------------------

  CREATE UNIQUE INDEX "EAE"."EAE_RESULTAT_INDEX" ON "EAE"."EAE_RESULTAT" ("ID_EAE", "ID_EAE_TYPE_OBJECTIF", "OBJECTIF") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PK_EAE_RESULTAT
--------------------------------------------------------

  CREATE UNIQUE INDEX "EAE"."PK_EAE_RESULTAT" ON "EAE"."EAE_RESULTAT" ("ID_EAE_RESULTAT") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PK_EAE_TYPE_DEVELOPPEMENT
--------------------------------------------------------

  CREATE UNIQUE INDEX "EAE"."PK_EAE_TYPE_DEVELOPPEMENT" ON "EAE"."EAE_TYPE_DEVELOPPEMENT" ("ID_EAE_TYPE_DEVELOPPEMENT") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PK_EAE_TYPE_RESULTAT
--------------------------------------------------------

  CREATE UNIQUE INDEX "EAE"."PK_EAE_TYPE_RESULTAT" ON "EAE"."EAE_TYPE_OBJECTIF" ("ID_EAE_TYPE_OBJECTIF") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table EAE
--------------------------------------------------------

  ALTER TABLE "EAE"."EAE" ADD CONSTRAINT "PK_EAE" PRIMARY KEY ("ID_EAE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
 
  ALTER TABLE "EAE"."EAE" MODIFY ("ID_EAE" NOT NULL ENABLE);
 
  ALTER TABLE "EAE"."EAE" MODIFY ("ID_CAMPAGNE_EAE" NOT NULL ENABLE);
 
  ALTER TABLE "EAE"."EAE" MODIFY ("ID_AGENT" NOT NULL ENABLE);
 
  ALTER TABLE "EAE"."EAE" MODIFY ("ETAT" NOT NULL ENABLE);
 
  ALTER TABLE "EAE"."EAE" MODIFY ("CAP" NOT NULL ENABLE);
 
  ALTER TABLE "EAE"."EAE" MODIFY ("DOC_ATTACHE" NOT NULL ENABLE);
 
  ALTER TABLE "EAE"."EAE" MODIFY ("VERSION" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table EAE_APPRECIATION
--------------------------------------------------------

  ALTER TABLE "EAE"."EAE_APPRECIATION" ADD CONSTRAINT "PK_EAE_APPRECIATION" PRIMARY KEY ("ID_EAE_APPRECIATION")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
 
  ALTER TABLE "EAE"."EAE_APPRECIATION" MODIFY ("ID_EAE_APPRECIATION" NOT NULL ENABLE);
 
  ALTER TABLE "EAE"."EAE_APPRECIATION" MODIFY ("ID_EAE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table EAE_AUTO_EVALUATION
--------------------------------------------------------

  ALTER TABLE "EAE"."EAE_AUTO_EVALUATION" ADD CONSTRAINT "PK_EAE_AUTO_EVALUATION" PRIMARY KEY ("ID_EAE_AUTO_EVALUATION")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
 
  ALTER TABLE "EAE"."EAE_AUTO_EVALUATION" MODIFY ("ID_EAE_AUTO_EVALUATION" NOT NULL ENABLE);
 
  ALTER TABLE "EAE"."EAE_AUTO_EVALUATION" MODIFY ("ID_EAE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table EAE_CAMPAGNE_ACTEURS
--------------------------------------------------------

  ALTER TABLE "EAE"."EAE_CAMPAGNE_ACTEURS" ADD CONSTRAINT "PK_CAMPAGNE_ACTEURS" PRIMARY KEY ("ID_CAMPAGNE_ACTEURS")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
 
  ALTER TABLE "EAE"."EAE_CAMPAGNE_ACTEURS" MODIFY ("ID_CAMPAGNE_ACTEURS" NOT NULL ENABLE);
 
  ALTER TABLE "EAE"."EAE_CAMPAGNE_ACTEURS" MODIFY ("ID_CAMPAGNE_ACTION" NOT NULL ENABLE);
 
  ALTER TABLE "EAE"."EAE_CAMPAGNE_ACTEURS" MODIFY ("ID_AGENT" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table EAE_CAMPAGNE_ACTION
--------------------------------------------------------

  ALTER TABLE "EAE"."EAE_CAMPAGNE_ACTION" ADD CONSTRAINT "PK_CAMPAGNE_ACTION" PRIMARY KEY ("ID_CAMPAGNE_ACTION")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
 
  ALTER TABLE "EAE"."EAE_CAMPAGNE_ACTION" MODIFY ("ID_CAMPAGNE_EAE" NOT NULL ENABLE);
 
  ALTER TABLE "EAE"."EAE_CAMPAGNE_ACTION" MODIFY ("NOM_ACTION" NOT NULL ENABLE);
 
  ALTER TABLE "EAE"."EAE_CAMPAGNE_ACTION" MODIFY ("MESSAGE" NOT NULL ENABLE);
 
  ALTER TABLE "EAE"."EAE_CAMPAGNE_ACTION" MODIFY ("DATE_TRANSMISSION" NOT NULL ENABLE);
 
  ALTER TABLE "EAE"."EAE_CAMPAGNE_ACTION" MODIFY ("DIFFUSE" NOT NULL ENABLE);
 
  ALTER TABLE "EAE"."EAE_CAMPAGNE_ACTION" MODIFY ("ID_AGENT_REALISATION" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table EAE_CAMPAGNE_EAE
--------------------------------------------------------

  ALTER TABLE "EAE"."EAE_CAMPAGNE_EAE" ADD CONSTRAINT "PK_CAMPAGNE_EAE" PRIMARY KEY ("ID_CAMPAGNE_EAE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
 
  ALTER TABLE "EAE"."EAE_CAMPAGNE_EAE" MODIFY ("ID_CAMPAGNE_EAE" NOT NULL ENABLE);
 
  ALTER TABLE "EAE"."EAE_CAMPAGNE_EAE" MODIFY ("ANNEE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table EAE_DEVELOPPEMENT
--------------------------------------------------------

  ALTER TABLE "EAE"."EAE_DEVELOPPEMENT" ADD CONSTRAINT "PK_EAE_DEVELOPPEMENT" PRIMARY KEY ("ID_EAE_DEVELOPPEMENT")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
 
  ALTER TABLE "EAE"."EAE_DEVELOPPEMENT" MODIFY ("ID_EAE_DEVELOPPEMENT" NOT NULL ENABLE);
 
  ALTER TABLE "EAE"."EAE_DEVELOPPEMENT" MODIFY ("ID_EAE" NOT NULL ENABLE);
 
  ALTER TABLE "EAE"."EAE_DEVELOPPEMENT" MODIFY ("ID_TYPE_DEVELOPPEMENT" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table EAE_DIPLOME
--------------------------------------------------------

  ALTER TABLE "EAE"."EAE_DIPLOME" ADD CONSTRAINT "PK_EAE_DIPLOME" PRIMARY KEY ("ID_EAE_DIPLOME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
 
  ALTER TABLE "EAE"."EAE_DIPLOME" MODIFY ("ID_EAE_DIPLOME" NOT NULL ENABLE);
 
  ALTER TABLE "EAE"."EAE_DIPLOME" MODIFY ("ID_EAE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table EAE_DOCUMENT
--------------------------------------------------------

  ALTER TABLE "EAE"."EAE_DOCUMENT" ADD CONSTRAINT "PK_EAE_DOCUMENT" PRIMARY KEY ("ID_EAE_DOCUMENT")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
 
  ALTER TABLE "EAE"."EAE_DOCUMENT" MODIFY ("ID_EAE_DOCUMENT" NOT NULL ENABLE);
 
  ALTER TABLE "EAE"."EAE_DOCUMENT" MODIFY ("ID_CAMPAGNE_EAE" NOT NULL ENABLE);
 
  ALTER TABLE "EAE"."EAE_DOCUMENT" MODIFY ("ID_DOCUMENT" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table EAE_EVALUATEUR
--------------------------------------------------------

  ALTER TABLE "EAE"."EAE_EVALUATEUR" ADD CONSTRAINT "PK_EAE_EVALUATEUR" PRIMARY KEY ("ID_EAE_EVALUATEUR")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
 
  ALTER TABLE "EAE"."EAE_EVALUATEUR" MODIFY ("ID_EAE_EVALUATEUR" NOT NULL ENABLE);
 
  ALTER TABLE "EAE"."EAE_EVALUATEUR" MODIFY ("ID_EAE" NOT NULL ENABLE);
 
  ALTER TABLE "EAE"."EAE_EVALUATEUR" MODIFY ("ID_AGENT" NOT NULL ENABLE);
 
  ALTER TABLE "EAE"."EAE_EVALUATEUR" MODIFY ("VERSION" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table EAE_EVALUATION
--------------------------------------------------------

  ALTER TABLE "EAE"."EAE_EVALUATION" ADD CONSTRAINT "PK_EAE_EVALUATION" PRIMARY KEY ("ID_EAE_EVALUATION")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
 
  ALTER TABLE "EAE"."EAE_EVALUATION" MODIFY ("ID_EAE_EVALUATION" NOT NULL ENABLE);
 
  ALTER TABLE "EAE"."EAE_EVALUATION" MODIFY ("ID_EAE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table EAE_EVALUE
--------------------------------------------------------

  ALTER TABLE "EAE"."EAE_EVALUE" ADD CONSTRAINT "PK_EAE_EVALUE" PRIMARY KEY ("ID_EAE_EVALUE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
 
  ALTER TABLE "EAE"."EAE_EVALUE" MODIFY ("ID_EAE_EVALUE" NOT NULL ENABLE);
 
  ALTER TABLE "EAE"."EAE_EVALUE" MODIFY ("ID_EAE" NOT NULL ENABLE);
 
  ALTER TABLE "EAE"."EAE_EVALUE" MODIFY ("ID_AGENT" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table EAE_EVOL_SOUHAIT
--------------------------------------------------------

  ALTER TABLE "EAE"."EAE_EVOL_SOUHAIT" ADD CONSTRAINT "PK_EAE_EVOL_SOUHAIT" PRIMARY KEY ("ID_EAE_EVOL_SOUHAIT")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
 
  ALTER TABLE "EAE"."EAE_EVOL_SOUHAIT" MODIFY ("ID_EAE_EVOL_SOUHAIT" NOT NULL ENABLE);
 
  ALTER TABLE "EAE"."EAE_EVOL_SOUHAIT" MODIFY ("ID_EAE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table EAE_EVOLUTION
--------------------------------------------------------

  ALTER TABLE "EAE"."EAE_EVOLUTION" ADD CONSTRAINT "PK_EAE_EVOLUTION" PRIMARY KEY ("ID_EAE_EVOLUTION")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
 
  ALTER TABLE "EAE"."EAE_EVOLUTION" MODIFY ("ID_EAE_EVOLUTION" NOT NULL ENABLE);
 
  ALTER TABLE "EAE"."EAE_EVOLUTION" MODIFY ("ID_EAE" NOT NULL ENABLE);
 
  ALTER TABLE "EAE"."EAE_EVOLUTION" MODIFY ("MOBILIE_GEO" NOT NULL ENABLE);
 
  ALTER TABLE "EAE"."EAE_EVOLUTION" MODIFY ("MOBILIE_FONCT" NOT NULL ENABLE);
 
  ALTER TABLE "EAE"."EAE_EVOLUTION" MODIFY ("CHANGEMENT_METIER" NOT NULL ENABLE);
 
  ALTER TABLE "EAE"."EAE_EVOLUTION" MODIFY ("MOBILITE_SERVICE" NOT NULL ENABLE);
 
  ALTER TABLE "EAE"."EAE_EVOLUTION" MODIFY ("MOBILITE_DIRECTION" NOT NULL ENABLE);
 
  ALTER TABLE "EAE"."EAE_EVOLUTION" MODIFY ("MOBILITE_COLLECTIVITE" NOT NULL ENABLE);
 
  ALTER TABLE "EAE"."EAE_EVOLUTION" MODIFY ("MOBILITE_AUTRE" NOT NULL ENABLE);
 
  ALTER TABLE "EAE"."EAE_EVOLUTION" MODIFY ("CONCOURS" NOT NULL ENABLE);
 
  ALTER TABLE "EAE"."EAE_EVOLUTION" MODIFY ("DEMANDE_VAE" NOT NULL ENABLE);
 
  ALTER TABLE "EAE"."EAE_EVOLUTION" MODIFY ("TEMPS_PARTIEL" NOT NULL ENABLE);
 
  ALTER TABLE "EAE"."EAE_EVOLUTION" MODIFY ("RETRAITE" NOT NULL ENABLE);
 
  ALTER TABLE "EAE"."EAE_EVOLUTION" MODIFY ("AUTRE_PERSPECTIVE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table EAE_FDP_ACTIVITE
--------------------------------------------------------

  ALTER TABLE "EAE"."EAE_FDP_ACTIVITE" ADD CONSTRAINT "PK_EAE_FDP_ACTIVITES" PRIMARY KEY ("ID_EAE_FDP_ACTIVITE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
 
  ALTER TABLE "EAE"."EAE_FDP_ACTIVITE" MODIFY ("ID_EAE_FDP_ACTIVITE" NOT NULL ENABLE);
 
  ALTER TABLE "EAE"."EAE_FDP_ACTIVITE" MODIFY ("ID_EAE_FICHE_POSTE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table EAE_FICHE_POSTE
--------------------------------------------------------

  ALTER TABLE "EAE"."EAE_FICHE_POSTE" ADD CONSTRAINT "PK_EAE_FICHE_POSTE" PRIMARY KEY ("ID_EAE_FICHE_POSTE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
 
  ALTER TABLE "EAE"."EAE_FICHE_POSTE" MODIFY ("ID_EAE_FICHE_POSTE" NOT NULL ENABLE);
 
  ALTER TABLE "EAE"."EAE_FICHE_POSTE" MODIFY ("ID_EAE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table EAE_FORMATION
--------------------------------------------------------

  ALTER TABLE "EAE"."EAE_FORMATION" ADD CONSTRAINT "PK_EAE_FORMATION" PRIMARY KEY ("ID_EAE_FORMATION")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
 
  ALTER TABLE "EAE"."EAE_FORMATION" MODIFY ("ID_EAE_FORMATION" NOT NULL ENABLE);
 
  ALTER TABLE "EAE"."EAE_FORMATION" MODIFY ("ID_EAE" NOT NULL ENABLE);
 
  ALTER TABLE "EAE"."EAE_FORMATION" MODIFY ("ANNEE_FORMATION" NOT NULL ENABLE);
 
  ALTER TABLE "EAE"."EAE_FORMATION" MODIFY ("DUREE_FORMATION" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table EAE_NIVEAU
--------------------------------------------------------

  ALTER TABLE "EAE"."EAE_NIVEAU" ADD CONSTRAINT "PK_EAE_NIVEAU_EAE" PRIMARY KEY ("ID_EAE_NIVEAU")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
 
  ALTER TABLE "EAE"."EAE_NIVEAU" MODIFY ("ID_EAE_NIVEAU" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table EAE_PARCOURS_PRO
--------------------------------------------------------

  ALTER TABLE "EAE"."EAE_PARCOURS_PRO" ADD CONSTRAINT "PK_EAE_PARCOURS_PRO" PRIMARY KEY ("ID_EAE_PARCOURS_PRO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
 
  ALTER TABLE "EAE"."EAE_PARCOURS_PRO" MODIFY ("ID_EAE_PARCOURS_PRO" NOT NULL ENABLE);
 
  ALTER TABLE "EAE"."EAE_PARCOURS_PRO" MODIFY ("ID_EAE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table EAE_PLAN_ACTION
--------------------------------------------------------

  ALTER TABLE "EAE"."EAE_PLAN_ACTION" ADD CONSTRAINT "PK_EAE_PLAN_ACTION" PRIMARY KEY ("ID_EAE_PLAN_ACTION")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
 
  ALTER TABLE "EAE"."EAE_PLAN_ACTION" MODIFY ("ID_EAE_PLAN_ACTION" NOT NULL ENABLE);
 
  ALTER TABLE "EAE"."EAE_PLAN_ACTION" MODIFY ("ID_EAE" NOT NULL ENABLE);
 
  ALTER TABLE "EAE"."EAE_PLAN_ACTION" MODIFY ("ID_EAE_TYPE_OBJECTIF" NOT NULL ENABLE);
 
  ALTER TABLE "EAE"."EAE_PLAN_ACTION" MODIFY ("VERSION" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table EAE_RESULTAT
--------------------------------------------------------

  ALTER TABLE "EAE"."EAE_RESULTAT" ADD CONSTRAINT "PK_EAE_RESULTAT" PRIMARY KEY ("ID_EAE_RESULTAT")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
 
  ALTER TABLE "EAE"."EAE_RESULTAT" MODIFY ("ID_EAE_RESULTAT" NOT NULL ENABLE);
 
  ALTER TABLE "EAE"."EAE_RESULTAT" MODIFY ("ID_EAE" NOT NULL ENABLE);
 
  ALTER TABLE "EAE"."EAE_RESULTAT" MODIFY ("ID_EAE_TYPE_OBJECTIF" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table EAE_TYPE_DEVELOPPEMENT
--------------------------------------------------------

  ALTER TABLE "EAE"."EAE_TYPE_DEVELOPPEMENT" ADD CONSTRAINT "PK_EAE_TYPE_DEVELOPPEMENT" PRIMARY KEY ("ID_EAE_TYPE_DEVELOPPEMENT")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
 
  ALTER TABLE "EAE"."EAE_TYPE_DEVELOPPEMENT" MODIFY ("ID_EAE_TYPE_DEVELOPPEMENT" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table EAE_TYPE_OBJECTIF
--------------------------------------------------------

  ALTER TABLE "EAE"."EAE_TYPE_OBJECTIF" ADD CONSTRAINT "PK_EAE_TYPE_RESULTAT" PRIMARY KEY ("ID_EAE_TYPE_OBJECTIF")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
 
  ALTER TABLE "EAE"."EAE_TYPE_OBJECTIF" MODIFY ("ID_EAE_TYPE_OBJECTIF" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table EAE
--------------------------------------------------------

  ALTER TABLE "EAE"."EAE" ADD CONSTRAINT "FK_EAE_CAMPAGNE_EAE" FOREIGN KEY ("ID_CAMPAGNE_EAE")
	  REFERENCES "EAE"."EAE_CAMPAGNE_EAE" ("ID_CAMPAGNE_EAE") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table EAE_APPRECIATION
--------------------------------------------------------

  ALTER TABLE "EAE"."EAE_APPRECIATION" ADD CONSTRAINT "FK_EAE_APPRECIATION" FOREIGN KEY ("ID_EAE")
	  REFERENCES "EAE"."EAE" ("ID_EAE") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table EAE_AUTO_EVALUATION
--------------------------------------------------------

  ALTER TABLE "EAE"."EAE_AUTO_EVALUATION" ADD CONSTRAINT "FK_EAE_AUTO_EVALUATION" FOREIGN KEY ("ID_EAE")
	  REFERENCES "EAE"."EAE" ("ID_EAE") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table EAE_CAMPAGNE_ACTEURS
--------------------------------------------------------

  ALTER TABLE "EAE"."EAE_CAMPAGNE_ACTEURS" ADD CONSTRAINT "FK_CAMPAGNE_ACTION" FOREIGN KEY ("ID_CAMPAGNE_ACTION")
	  REFERENCES "EAE"."EAE_CAMPAGNE_ACTION" ("ID_CAMPAGNE_ACTION") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table EAE_CAMPAGNE_ACTION
--------------------------------------------------------

  ALTER TABLE "EAE"."EAE_CAMPAGNE_ACTION" ADD CONSTRAINT "FK_CAMPAGNE_EAE" FOREIGN KEY ("ID_CAMPAGNE_EAE")
	  REFERENCES "EAE"."EAE_CAMPAGNE_EAE" ("ID_CAMPAGNE_EAE") ENABLE;

--------------------------------------------------------
--  Ref Constraints for Table EAE_DEVELOPPEMENT
--------------------------------------------------------

  ALTER TABLE "EAE"."EAE_DEVELOPPEMENT" ADD CONSTRAINT "FK_EAE_DEVELOPPEMENT" FOREIGN KEY ("ID_EAE")
	  REFERENCES "EAE"."EAE" ("ID_EAE") ENABLE;
 
  ALTER TABLE "EAE"."EAE_DEVELOPPEMENT" ADD CONSTRAINT "FK_EAE_TYPE_DEVELOPPEMENT" FOREIGN KEY ("ID_TYPE_DEVELOPPEMENT")
	  REFERENCES "EAE"."EAE_TYPE_DEVELOPPEMENT" ("ID_EAE_TYPE_DEVELOPPEMENT") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table EAE_DIPLOME
--------------------------------------------------------

  ALTER TABLE "EAE"."EAE_DIPLOME" ADD CONSTRAINT "FK_EAE_DIPLOME" FOREIGN KEY ("ID_EAE")
	  REFERENCES "EAE"."EAE" ("ID_EAE") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table EAE_DOCUMENT
--------------------------------------------------------

  ALTER TABLE "EAE"."EAE_DOCUMENT" ADD CONSTRAINT "FK_EAE_DOCUMENT" FOREIGN KEY ("ID_CAMPAGNE_EAE")
	  REFERENCES "EAE"."EAE_CAMPAGNE_EAE" ("ID_CAMPAGNE_EAE") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table EAE_EVALUATEUR
--------------------------------------------------------

  ALTER TABLE "EAE"."EAE_EVALUATEUR" ADD CONSTRAINT "FK_EAE_EVALUATEUR" FOREIGN KEY ("ID_EAE")
	  REFERENCES "EAE"."EAE" ("ID_EAE") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table EAE_EVALUATION
--------------------------------------------------------

  ALTER TABLE "EAE"."EAE_EVALUATION" ADD CONSTRAINT "FK_EAE_EVALUATION" FOREIGN KEY ("ID_EAE")
	  REFERENCES "EAE"."EAE" ("ID_EAE") ENABLE;
 
  ALTER TABLE "EAE"."EAE_EVALUATION" ADD CONSTRAINT "FK_EAE_NIVEAU_EAE" FOREIGN KEY ("ID_EAE_NIVEAU")
	  REFERENCES "EAE"."EAE_NIVEAU" ("ID_EAE_NIVEAU") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table EAE_EVALUE
--------------------------------------------------------

  ALTER TABLE "EAE"."EAE_EVALUE" ADD CONSTRAINT "FK_EAE_EVALUE" FOREIGN KEY ("ID_EAE")
	  REFERENCES "EAE"."EAE" ("ID_EAE") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table EAE_EVOL_SOUHAIT
--------------------------------------------------------

  ALTER TABLE "EAE"."EAE_EVOL_SOUHAIT" ADD CONSTRAINT "FK_EAE_EVOL_SOUHAIT" FOREIGN KEY ("ID_EAE")
	  REFERENCES "EAE"."EAE" ("ID_EAE") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table EAE_EVOLUTION
--------------------------------------------------------

  ALTER TABLE "EAE"."EAE_EVOLUTION" ADD CONSTRAINT "FK_EAE_EVOLUTION" FOREIGN KEY ("ID_EAE")
	  REFERENCES "EAE"."EAE" ("ID_EAE") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table EAE_FDP_ACTIVITE
--------------------------------------------------------

  ALTER TABLE "EAE"."EAE_FDP_ACTIVITE" ADD CONSTRAINT "FK_EAE_FDP_ACTIVITES" FOREIGN KEY ("ID_EAE_FICHE_POSTE")
	  REFERENCES "EAE"."EAE_FICHE_POSTE" ("ID_EAE_FICHE_POSTE") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table EAE_FICHE_POSTE
--------------------------------------------------------

  ALTER TABLE "EAE"."EAE_FICHE_POSTE" ADD CONSTRAINT "FK_EAE_FICHE_POSTE" FOREIGN KEY ("ID_EAE")
	  REFERENCES "EAE"."EAE" ("ID_EAE") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table EAE_FORMATION
--------------------------------------------------------

  ALTER TABLE "EAE"."EAE_FORMATION" ADD CONSTRAINT "FK_EAE_FORMATION" FOREIGN KEY ("ID_EAE")
	  REFERENCES "EAE"."EAE" ("ID_EAE") ENABLE;

--------------------------------------------------------
--  Ref Constraints for Table EAE_PARCOURS_PRO
--------------------------------------------------------

  ALTER TABLE "EAE"."EAE_PARCOURS_PRO" ADD CONSTRAINT "FK_EAE_PARCOURS_PRO" FOREIGN KEY ("ID_EAE")
	  REFERENCES "EAE"."EAE" ("ID_EAE") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table EAE_PLAN_ACTION
--------------------------------------------------------

  ALTER TABLE "EAE"."EAE_PLAN_ACTION" ADD CONSTRAINT "FK_EAE_PLAN_ACTION" FOREIGN KEY ("ID_EAE")
	  REFERENCES "EAE"."EAE" ("ID_EAE") ENABLE;
 
  ALTER TABLE "EAE"."EAE_PLAN_ACTION" ADD CONSTRAINT "FK_EAE_TYPE_RES_PLAN_ACTION" FOREIGN KEY ("ID_EAE_TYPE_OBJECTIF")
	  REFERENCES "EAE"."EAE_TYPE_OBJECTIF" ("ID_EAE_TYPE_OBJECTIF") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table EAE_RESULTAT
--------------------------------------------------------

  ALTER TABLE "EAE"."EAE_RESULTAT" ADD CONSTRAINT "FK_EAE_RESULTAT" FOREIGN KEY ("ID_EAE")
	  REFERENCES "EAE"."EAE" ("ID_EAE") ENABLE;
 
  ALTER TABLE "EAE"."EAE_RESULTAT" ADD CONSTRAINT "FK_EAE_TYPE_RESULTAT" FOREIGN KEY ("ID_EAE_TYPE_OBJECTIF")
	  REFERENCES "EAE"."EAE_TYPE_OBJECTIF" ("ID_EAE_TYPE_OBJECTIF") ENABLE;

create sequence EAE_S_CAMPAGNE_EAE 
start with 1 
increment by 1 
nomaxvalue;
create sequence EAE_S_CAMPAGNE_ACTION 
start with 1 
increment by 1 
nomaxvalue; 
create sequence EAE_S_CAMPAGNE_ACTEURS 
start with 1 
increment by 1 
nomaxvalue; 
create sequence EAE_S_EAE 
start with 1 
increment by 1 
nomaxvalue; 
create sequence EAE_S_EVALUATEUR 
start with 1 
increment by 1 
nomaxvalue; 
create sequence EAE_S_EVALUE 
start with 1 
increment by 1 
nomaxvalue; 
create sequence EAE_S_FICHE_POSTE 
start with 1 
increment by 1 
nomaxvalue; 
create sequence EAE_S_FDP_ACTIVITE 
start with 1 
increment by 1 
nomaxvalue; 
create sequence EAE_S_DIPLOME 
start with 1 
increment by 1 
nomaxvalue; 
create sequence EAE_S_PARCOURS_PRO 
start with 1 
increment by 1 
nomaxvalue; 
create sequence EAE_S_FORMATION 
start with 1 
increment by 1 
nomaxvalue; 
create sequence EAE_S_TYPE_OBJECTIF 
start with 1 
increment by 1 
nomaxvalue;
create sequence EAE_S_RESULTAT 
start with 1 
increment by 1 
nomaxvalue;
create sequence EAE_S_PLAN_ACTION 
start with 1 
increment by 1 
nomaxvalue; 
create sequence EAE_S_NIVEAU 
start with 1 
increment by 1 
nomaxvalue;
create sequence EAE_S_EVALUATION 
start with 1 
increment by 1 
nomaxvalue; 
create sequence EAE_S_DOCUMENT 
start with 1 
increment by 1 
nomaxvalue;
create sequence EAE_S_APPRECIATION 
start with 1 
increment by 1 
nomaxvalue; 
create sequence EAE_S_AUTO_EVALUATION 
start with 1 
increment by 1 
nomaxvalue; 
create sequence EAE_S_EVOLUTION 
start with 1 
increment by 1 
nomaxvalue; 
create sequence EAE_S_EVOL_SOUHAIT 
start with 1 
increment by 1 
nomaxvalue; 
create sequence EAE_S_TYPE_DEVELOPPEMENT 
start with 1 
increment by 1 
nomaxvalue; 
create sequence EAE_S_DEVELOPPEMENT 
start with 1 
increment by 1 
nomaxvalue; 

-- DB AGENT (AS400 MOCK)
INSERT INTO AGENT VALUES(9007000,'3884-05-19',NULL,'Nom SHD+3',NULL,9007000,'Pr\u005cu00e9nom SHD+3','Pr\u005cu00e9nom SHD+3')
INSERT INTO AGENT VALUES(9007001,'3884-05-19',NULL,'Nom SHD+2',NULL,9007000,'Pr\u005cu00e9nom SHD+2','Pr\u005cu00e9nom SHD+2')
INSERT INTO AGENT VALUES(9007002,'3884-05-19',NULL,'Nom SHD+2',NULL,9007000,'Pr\u005cu00e9nom SHD+2','Pr\u005cu00e9nom SHD+2')
INSERT INTO AGENT VALUES(9007003,'3884-05-19',NULL,'Nom SHD+1',NULL,9007000,'Pr\u005cu00e9nom SHD+1','Pr\u005cu00e9nom SHD+1')
INSERT INTO AGENT VALUES(9007004,'3884-05-19',NULL,'Nom Eval1',NULL,9007000,'Pr\u005cu00e9nom Eval1','Pr\u005cu00e9nom Eval1')
INSERT INTO AGENT VALUES(9007005,'3884-05-19',NULL,'Nom Eval2',NULL,9007000,'Pr\u005cu00e9nom Eval2','Pr\u005cu00e9nom Eval2')
INSERT INTO AGENT VALUES(9007006,'3884-05-19',NULL,'Nom SHD+1',NULL,9007000,'Pr\u005cu00e9nom SHD+1','Pr\u005cu00e9nom SHD+1')
INSERT INTO AGENT VALUES(9007007,'3884-05-19',NULL,'Nom Eval3',NULL,9007000,'Pr\u005cu00e9nom Eval3','Pr\u005cu00e9nom Eval3')
INSERT INTO AGENT VALUES(9007008,'3884-05-19',NULL,'Nom SHD+1',NULL,9007000,'Pr\u005cu00e9nom SHD+1','Pr\u005cu00e9nom SHD+1')
INSERT INTO AGENT VALUES(9007009,'3884-05-19',NULL,'Nom Eval4',NULL,9007000,'Pr\u005cu00e9nom Eval4','Pr\u005cu00e9nom Eval4')
INSERT INTO AGENT VALUES(9007010,'3884-05-19',NULL,'Nom Eval5',NULL,9007000,'Pr\u005cu00e9nom Eval5','Pr\u005cu00e9nom Eval5')
