// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package nc.moumea.mairie.sirh.eae.domain;

import nc.moumea.mairie.sirh.eae.domain.Eae;

privileged aspect Eae_Roo_JavaBean {
    
    public String Eae.getAgent() {
        return this.Agent;
    }
    
    public void Eae.setAgent(String Agent) {
        this.Agent = Agent;
    }
    
}
