// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package nc.noumea.mairie.sirh.eae.domain;

import nc.noumea.mairie.sirh.eae.domain.EaeCommentaire;

privileged aspect EaeCommentaire_Roo_JavaBean {
    
    public String EaeCommentaire.getText() {
        return this.text;
    }
    
    public void EaeCommentaire.setText(String text) {
        this.text = text;
    }
    
}
