// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package nc.noumea.mairie.sirh.eae.domain;

import nc.noumea.mairie.sirh.eae.domain.EaeCampagne;

privileged aspect EaeCampagne_Roo_JavaBean {
    
    public int EaeCampagne.getAnnee() {
        return this.annee;
    }
    
    public void EaeCampagne.setAnnee(int annee) {
        this.annee = annee;
    }
    
}
