// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package nc.noumea.mairie.sirh.eae.domain;

import nc.noumea.mairie.sirh.eae.domain.EaeFichePoste;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect EaeFichePoste_Roo_Configurable {
    
    declare @type: EaeFichePoste: @Configurable;
    
}
