language: java
jdk:
- oraclejdk8
cache:
  directories:
  - "$HOME/.m2"
before_install:
- export TZ=Pacific/Noumea
install: mvn -DcreateChecksum=true clean install
env:
  global:
  - secure: N83zCfsem5pB2HxEZp/Ku3icboIGtgZeC02qP6OHf+jPp/0g+udlT8GyGCS9BtqhWeOPA+jl47g8XI8gQyluJ07D5keLrg8Zp0esGaAJfQ4ttYEFrD3zFGmdGjTgugnWb7vKmuki6HYIJldrgAMfbM6fNl54ij7E5WhNDtT2TrUFXkGTtGR8RfBXUi6CiXK5FK4PzXlP544dbVkI9OSlNDOQaZPc9Od3bp2rMBd0V+mrJczISRaBYdLYovA2P714z41QGCxJzzNUOdlck/E0OfctGSGLpNMpaLX4BRFkWm7XWwbFnlXK7jzCStophbDfGy+00/iw97gia/+gACyqgT4fBGDdlwzyN+BGUq2ub57AnVggMkLnQaj5hHtedxu44jU21RsMUGIUjwozV60FiS5v6tMZusvI3j7hcEowCDuXUlhIm7LrYAmp6or6FvQQAUp4NH2B7u6bPzM0ohW0LO9suBmmLkV8LA/4HJIc3UX7BHqzT1lThAPLLgnMuHaJYwNjgEVmNFCKMRUMihlqaaJlIIDnabGsGJUyk7ZHeETycC5iuh22o2cziDRMhRg7Q5uoL1pEEoXxWfvXLQOnXwJJhhx4hknoJVPng0Gb2ml0mRAeket33W7IfDAsL+IaNgFeTvehG7TRvWTQZPahLo+d+JS7wNQorop+N+Yao8A=
  - secure: AfZi1A4hYyVla+zlsvxA/yCEWla7dDlUuXvGGJ13aojrVIJ+XQBYEY6Igaty0jNLjX5+cev/QR3bqVN+rLRIAsUz7uXlBuXEMt9ifZKv7DjbpHKAKvzFh4MZdLPMyPUhQTAc4ohW0EW292nqoB6kLVflI0Cd6kgJ0LnMLxClr36oOetLOhCZGj4z8YUkT+sMrlbwgLVjXun1qWwuOVfFZizdKWLAStnFPVd3hladcHTGvX6ib62a8dLUiRaR+ET+UVlHIF/ZwvLW5vwTnviO4uIURwBrQFu1H+c+WHbg6rv3n9kFxzNun7Y7qmjxHfHSJC2r+jwpcvk5MlWqyMaoB/JAhDgyAX8ZghMAXZss0hidVs46lIOEU8m1aQ9XPLBhXi/PMWlXJzU/9DpIXzkO/HIUcLPQB8me9vYhOEvRN+E2oQEueLIq9XZEf8GUUHSKig23G84vlsohB2zckts9eJ8DgJt9qGoou7Sx8cGa3n43i7VbbgEoeH+KwVnQl/XHEAf71ykoo+Ndp7Ktu9XlRf2NOZTAblGJPrePAPxU85dYb8UoAYY95+7f3wRFyK6kDiLCNk/I9DZUkE9M1FPUuhvbPpVxH0cyuRh55mLiIAsQD2S1oMDQT4MpiUEvCr/CcVbXVV0AVBrFr4bwyG52BwOYoMH1KJFzbdqOicExTLM=
  - secure: gtktgO40papVTm8LDQG3ZM3JjHo90OZNtFTfi/dQEM2ilRrRjKQLv5o/65vkwebz2WsdjQP8IgfmU3hOy50/lj41HJK7kbnSlo1wmER44vZXKtzzeViXcpMP/KNqoJ81jhb0FRcZiw65r31VIOlaeH/8RukcExAT2GM7m5d8htJ+TuxdXdS0L8JxP2Xn+nnFEzrTrOOXYXQ2LOvTcbU9oe+mq/f4NudwFNjdlY1p7xCp3VSMCCvHuv8OYZPKGUVxxLNAizL7EOOaJ/ImMHSZmg+praODeoWVdI+74pT/iz629JaTU3US4o03umU/KftmYOJhi6ojulr04L606bTaObKB0kM9FNpTas+M8yQjj6Ij0cLsJlmPfL5dS3aowpYA34HeEdngtsXLZNDqVnqZ5dkeQPhcmsY1naPwp4CqtHCD38/ja3BZ9nRHxYTA8LtN96Mk/DnzzjBRF8G4XU+/bmOubtwXFVHhzXi0QGDijOjNhnQbU8/lDiX6gZ7Mu2aPdq8ipHT3DMI/oz595buz1zr5idPfpYhZ+Ruo2ArMv4qmjL+p6dWskVFG+w6IgEdUCC7DcSUXNwnbRWgVhAh/wY/y7rZpBK6VUQwrB2tNt6VrePjpoeolclSSOR0niBVjWi9z5xqPwXvakPZ9wZ8VThggT4DK7V5LmAitd6DxUKE=
script:
- mvn versioneye:update test jacoco:report org.jacoco:jacoco-maven-plugin:prepare-agent
  install
after_success:
- mvn coveralls:report
notifications:
  slack:
    secure: RfvsovXhZDoY1qSFPqeBvXi83kRB3ITP+rRoLMV6EP4uUlB66KgdwhDPAwJGfMZ/b5dHr9u/vMdj9/JJTzLqzZHXaaiQvzg8CI6Xf1Fj2XfaBrZkjREBHjPHJbxnWPlGIP4/IuCzw90UAZDAVWw1xOSd0zULXvUZfnN2f+JnWZSYCV+fAOr7Cs7cHcBGtnL7Gs3Ad4AqG2K348F8IPq+ua63Yyfvw2ssa+K4ZDp/yRxqF1knrB0ojujms0P3Fh4xr550onTOptNnmvbmHUMyWUcFbcLZhhlQILKUZ361viyuPVmzXiOgKB0i4LrAMLVy2RJpqurHxy456UceowVWGvcJWXNdIHkmYunIZqRF0PRsiYLoBfa37w3Cq+URhgkRBoVmPtM9Dko980wPAfjfTxT+t5J376hoiaeib6j3ggHcXOsWi0y+9EzFpzl5aCF8eYbRFFG7Pq0o5UEyQmpBnttr4fXcycziKUcAIHmuCU4GI7soY8hllmtGhVFDuz8AEC3DqZ+isF8PKP4DSnnkmRx2qYeBNJOHnlVHsGVoTHrnnAVQW06yh8zfAQS89OwcFlPUSg/To+jVRAgK/bDQ0zs4z0ZMDw3Ep0GRtGkbJdwDCfeUBBOTiGy3XQEBuvXhcgoEEuML7/ZrrAusv1+V7kAnTa3/WSwA/HOKSfu/9J4=
before_deploy:
- export RELEASE_PKG_FILE=$(ls target/*.war)
- export RELEASE_PKG_MD5_FILE=$(ls target/*.war.md5)
- export RELEASE_PKG_SHA_FILE=$(ls target/*.war.sha1)
- echo "deploying $RELEASE_PKG_FILE , $RELEASE_PKG_MD5_FILE , $RELEASE_PKG_SHA_FILE
  to GitHub releases"
deploy:
  provider: releases
  api_key:
    secure: VK2Rrq2xnq807zO0H/GeSe9cuCdYr6zya+EsfBS/JmBoJjmeI1lKyIRHgb3AuEwpyX7LdcCnhg/tkTWVTaC7qe5a78AAiOwdLzT46ZDGatYuFsx4WTnEuP4iijLUpujgtPqZV1UaNS2UiT+ouTStjwWM56OGMIMqDkxm6VzzUGIHV08A0CtCPWnJ3cLkb/7xBxXcUa2RaqHFrRixiT1Ho3T+pipRXUNojHmFN4hXKf9ULAQpZr83/u91EjVvCIov9wcWt81I21GGaMl7KDuLnTgxRIdwt5U6+DRrDOEl3Y04tKEWDeAGtNsv9qISVgdVUFUyXVqCigSdjxWNA0wcij+M445l0KjKG1VYwQ+zZEy7UG4v9u0LEVD7V73TJ+/T+598X0zMjE7zG2x4hu1bZ/lNZzbcTARFbgI1HvI0AHMxJ53kQPXzpkN8h96Bwn4qmjfq9GRLq0jV9pisuiocH5fNwA3pDzTISEpUus+saAAlNs6NAK3bg30zOa0QGsNMW7fGckmTV8c8D6FO2VaS6+kMwGgHuFEPEKBfSofuvN+ioGxecSCD3lTdjubDcUpfQZI3oZIx2mCGL8u+K8yMoCDm9HuCmPogcz1sSKrM+ZDwb/03bzw9mnVDhjXwSmNmoqceKgByd5vtawsGFzowmaZZrfh++1lyJDrwq3ZiBUc=
  file:
    - ${RELEASE_PKG_FILE}
    - ${RELEASE_PKG_MD5_FILE}
    - ${RELEASE_PKG_SHA_FILE}
  skip_cleanup: true
  on:
    tags: true
    repo: DSI-Ville-Noumea/sirh-eae-ws