// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package nc.noumea.mairie.sirh.domain;

import java.util.Date;
import nc.noumea.mairie.sirh.domain.Agent;

privileged aspect Agent_Roo_JavaBean {
    
    public Integer Agent.getNomatr() {
        return this.nomatr;
    }
    
    public void Agent.setNomatr(Integer nomatr) {
        this.nomatr = nomatr;
    }
    
    public String Agent.getNomMarital() {
        return this.nomMarital;
    }
    
    public void Agent.setNomMarital(String nomMarital) {
        this.nomMarital = nomMarital;
    }
    
    public String Agent.getNomPatronymique() {
        return this.nomPatronymique;
    }
    
    public void Agent.setNomPatronymique(String nomPatronymique) {
        this.nomPatronymique = nomPatronymique;
    }
    
    public String Agent.getNomUsage() {
        return this.nomUsage;
    }
    
    public void Agent.setNomUsage(String nomUsage) {
        this.nomUsage = nomUsage;
    }
    
    public String Agent.getPrenom() {
        return this.prenom;
    }
    
    public void Agent.setPrenom(String prenom) {
        this.prenom = prenom;
    }
    
    public String Agent.getPrenomUsage() {
        return this.prenomUsage;
    }
    
    public void Agent.setPrenomUsage(String prenomUsage) {
        this.prenomUsage = prenomUsage;
    }
    
    public Date Agent.getDateNaissance() {
        return this.dateNaissance;
    }
    
    public void Agent.setDateNaissance(Date dateNaissance) {
        this.dateNaissance = dateNaissance;
    }
    
}
