-- Connecte en EAE_ADM
alter table EAE_FICHE_POSTE add (DATE_ENTREE_SERVICE_RESP DATE);
alter table EAE_FICHE_POSTE add (DATE_ENTREE_COLLECT_RESP DATE);
alter table EAE_FICHE_POSTE add (DATE_ENTREE_FONCTION_RESP DATE);
alter table EAE_FICHE_POSTE add (CODE_SERVICE VARCHAR2(4));