-- Connecte en EAE_USR
insert into EAE_TYPE_OBJECTIF (ID_EAE_TYPE_OBJECTIF, LIBELLE_TYPE_OBJECTIF) values (EAE_S_TYPE_OBJECTIF.nextval,'PROFESSIONNEL');
insert into EAE_TYPE_OBJECTIF (ID_EAE_TYPE_OBJECTIF, LIBELLE_TYPE_OBJECTIF) values (EAE_S_TYPE_OBJECTIF.nextval,'INDIVIDUEL');
insert into EAE_TYPE_OBJECTIF (ID_EAE_TYPE_OBJECTIF, LIBELLE_TYPE_OBJECTIF) values (EAE_S_TYPE_OBJECTIF.nextval,'MATERIELS');
insert into EAE_TYPE_OBJECTIF (ID_EAE_TYPE_OBJECTIF, LIBELLE_TYPE_OBJECTIF) values (EAE_S_TYPE_OBJECTIF.nextval,'FINANCIERS');
insert into EAE_TYPE_OBJECTIF (ID_EAE_TYPE_OBJECTIF, LIBELLE_TYPE_OBJECTIF) values (EAE_S_TYPE_OBJECTIF.nextval,'AUTRES');

insert into EAE_TYPE_DEVELOPPEMENT (ID_EAE_TYPE_DEVELOPPEMENT, LIBELLE_TYPE_DEVELOPPEMENT) values (EAE_S_TYPE_DEVELOPPEMENT.nextval,'CONNAISSANCE');
insert into EAE_TYPE_DEVELOPPEMENT (ID_EAE_TYPE_DEVELOPPEMENT, LIBELLE_TYPE_DEVELOPPEMENT) values (EAE_S_TYPE_DEVELOPPEMENT.nextval,'COMPETENCE');
insert into EAE_TYPE_DEVELOPPEMENT (ID_EAE_TYPE_DEVELOPPEMENT, LIBELLE_TYPE_DEVELOPPEMENT) values (EAE_S_TYPE_DEVELOPPEMENT.nextval,'CONCOURS');
insert into EAE_TYPE_DEVELOPPEMENT (ID_EAE_TYPE_DEVELOPPEMENT, LIBELLE_TYPE_DEVELOPPEMENT) values (EAE_S_TYPE_DEVELOPPEMENT.nextval,'PERSONNEL');
insert into EAE_TYPE_DEVELOPPEMENT (ID_EAE_TYPE_DEVELOPPEMENT, LIBELLE_TYPE_DEVELOPPEMENT) values (EAE_S_TYPE_DEVELOPPEMENT.nextval,'COMPORTEMENT');
insert into EAE_TYPE_DEVELOPPEMENT (ID_EAE_TYPE_DEVELOPPEMENT, LIBELLE_TYPE_DEVELOPPEMENT) values (EAE_S_TYPE_DEVELOPPEMENT.nextval,'FORMATEUR');


insert into EAE_NIVEAU (ID_EAE_NIVEAU, LIBELLE_NIVEAU_EAE) values (EAE_S_NIVEAU.nextval,'EXCELLENT');
insert into EAE_NIVEAU (ID_EAE_NIVEAU, LIBELLE_NIVEAU_EAE) values (EAE_S_NIVEAU.nextval,'SATISFAISANT');
insert into EAE_NIVEAU (ID_EAE_NIVEAU, LIBELLE_NIVEAU_EAE) values (EAE_S_NIVEAU.nextval,'NECESSITANT DES PROGRES');
insert into EAE_NIVEAU (ID_EAE_NIVEAU, LIBELLE_NIVEAU_EAE) values (EAE_S_NIVEAU.nextval,'INSUFFISANT');

commit;
