----------------------------------------------------------------
-- Connecte en EAE_ADM
----------------------------------------------------------------

GRANT SELECT ON EAE_ADM.EAE_EVALUE TO R_SIRH_WS_RO;

GRANT SELECT ON EAE_ADM.EAE_CAMPAGNE_EAE TO R_EAE_JOBS_USR;
GRANT SELECT ON EAE_ADM.EAE_CAMPAGNE_ACTEURS TO R_EAE_JOBS_USR;
GRANT SELECT ON EAE_ADM.EAE_DOCUMENT TO R_EAE_JOBS_USR;
GRANT SELECT, UPDATE ON EAE_ADM.EAE_CAMPAGNE_ACTION TO R_EAE_JOBS_USR;
