----------------------------------------------------------------
-- Connecte en EAE_ADM
----------------------------------------------------------------

REVOKE INSERT,UPDATE ON EAE_ADM.EAE_COMMENTAIRE FROM R_SIRH_WS_RO;
REVOKE INSERT,UPDATE,DELETE ON EAE_ADM.EAE_PLAN_ACTION FROM R_SIRH_WS_RO;
REVOKE UPDATE ON EAE_ADM.EAE_EVOLUTION FROM R_SIRH_WS_RO;
REVOKE INSERT,UPDATE,DELETE ON EAE_ADM.EAE_DEVELOPPEMENT FROM R_SIRH_WS_RO;
REVOKE UPDATE ON EAE_ADM.EAE_EVALUATION FROM R_SIRH_WS_RO;
REVOKE SELECT ON EAE_ADM.EAE_S_COMMENTAIRE FROM R_SIRH_WS_RO;
REVOKE SELECT ON EAE_ADM.EAE_TYPE_DEVELOPPEMENT FROM R_SIRH_WS_RO;
REVOKE SELECT ON EAE_ADM.EAE_S_TYPE_DEVELOPPEMENT FROM R_SIRH_WS_RO;

GRANT SELECT,INSERT,UPDATE ON EAE_ADM.EAE_COMMENTAIRE TO R_SIRH_USR;
GRANT SELECT,INSERT,UPDATE,DELETE ON EAE_ADM.EAE_PLAN_ACTION TO R_SIRH_USR;
GRANT SELECT,UPDATE ON EAE_ADM.EAE_EVOLUTION TO R_SIRH_USR;
GRANT SELECT,INSERT,UPDATE,DELETE ON EAE_ADM.EAE_DEVELOPPEMENT TO R_SIRH_USR;
GRANT UPDATE ON EAE_ADM.EAE_EVALUATION TO R_SIRH_USR;
GRANT SELECT ON EAE_ADM.EAE_TYPE_DEVELOPPEMENT TO R_SIRH_USR;
GRANT SELECT ON EAE_ADM.EAE_S_COMMENTAIRE TO R_SIRH_USR;
GRANT SELECT ON EAE_ADM.EAE_S_FINALISATION TO R_SIRH_USR;
GRANT SELECT ON EAE_ADM.EAE_S_TYPE_DEVELOPPEMENT TO R_SIRH_USR;


