----------------------------------------------------------------
-- Connecte en EAE_ADM
----------------------------------------------------------------

GRANT SELECT,INSERT,UPDATE ON EAE_ADM.EAE_COMMENTAIRE TO R_SIRH_WS_RO;
GRANT SELECT ON EAE_ADM.EAE_S_COMMENTAIRE TO R_SIRH_WS_RO;
GRANT SELECT ON EAE_ADM.EAE_S_FINALISATION TO R_SIRH_WS_RO;
GRANT SELECT ON EAE_ADM.EAE_PLAN_ACTION TO R_SIRH_WS_RO;
GRANT SELECT ON EAE_ADM.EAE_EVOLUTION TO R_SIRH_WS_RO;
GRANT SELECT ON EAE_ADM.EAE_DEVELOPPEMENT TO R_SIRH_WS_RO;


