----------------------------------------------------------------
-- Connecte en EAE_ADM
----------------------------------------------------------------

GRANT SELECT ON EAE_ADM.EAE_S_EVOLUTION TO R_SIRH_USR;
GRANT INSERT ON EAE_ADM.EAE_EVOLUTION TO R_SIRH_USR;


GRANT UPDATE ON EAE_ADM.EAE_S_NUM_INCREMENT_DOCUMENT TO R_SIRH_USR; --> CETTE COMMANDE NE FONCTIONNE PAS ET NE DOIT PAS ETRE UTILISEE.LA FONCTION NEXTVAL FAIT L'INCREMENTATION.



