// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package nc.moumea.mairie.sirh.domain;

import nc.moumea.mairie.sirh.domain.Agent;

privileged aspect Agent_Roo_JavaBean {
    
    public Integer Agent.getNomatr() {
        return this.nomatr;
    }
    
    public void Agent.setNomatr(Integer nomatr) {
        this.nomatr = nomatr;
    }
    
    public String Agent.getNomMarital() {
        return this.nomMarital;
    }
    
    public void Agent.setNomMarital(String nomMarital) {
        this.nomMarital = nomMarital;
    }
    
    public String Agent.getNomPatronymique() {
        return this.nomPatronymique;
    }
    
    public void Agent.setNomPatronymique(String nomPatronymique) {
        this.nomPatronymique = nomPatronymique;
    }
    
}
